name: IP延迟测试

on:
  workflow_dispatch:
    inputs:
      countries:
        description: '目标国家列表（逗号分隔）'
        required: false
        default: 'US'
        type: string
      counts:
        description: '每个国家的目标IP数量（逗号分隔）'
        required: false
        default: '3'
        type: string
      batch_size:
        description: '每批处理的IP数量'
        required: false
        default: '20'
        type: number
      max_ips:
        description: '最大IP数量限制（0表示无限制）'
        required: false
        default: '0'
        type: number
      concurrent:
        description: '并发测试数量'
        required: false
        default: '10'
        type: number
      ports:
        description: '测试端口（逗号分隔）'
        required: false
        default: '443'
        type: string

jobs:
  ip-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install aiohttp

    - name: 运行IP测试
      run: |
        python ip_tester.py \
          --countries "${{ github.event.inputs.countries }}" \
          --counts "${{ github.event.inputs.counts }}" \
          --batch-size ${{ github.event.inputs.batch_size }} \
          --max-ips ${{ github.event.inputs.max_ips }} \
          --concurrent ${{ github.event.inputs.concurrent }} \
          --ports "${{ github.event.inputs.ports }}" \
          --output ip_results

    - name: 上传测试结果
      uses: actions/upload-artifact@v4
      with:
        name: ip-results
        path: ip_results/
        retention-days: 7