name: IP Tester

on:
  # 每3小时自动运行
  schedule:
    - cron: '0 */3 * * *'
  # 允许手动触发，支持参数
  workflow_dispatch:
    inputs:
      target_countries:
        description: '目标国家代码列表（逗号分隔，如：JP,SG,US）'
        required: false
        default: 'JP,SG,US'
        type: string
      min_ips_per_country:
        description: '每个国家最少IP数量'
        required: false
        default: '3'
        type: string
      max_concurrent:
        description: '最大并发数'
        required: false
        default: '30'
        type: string

jobs:
  test-ips:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run IP tester with parameters
      run: |
        # 构建参数
        TARGET_COUNTRIES="${{ github.event.inputs.target_countries || 'JP,SG,US' }}"
        MIN_IPS_PER_COUNTRY="${{ github.event.inputs.min_ips_per_country || '3' }}"
        MAX_CONCURRENT="${{ github.event.inputs.max_concurrent || '30' }}"
        TEST_CHINA_NETWORK="${{ github.event.inputs.test_china_network || 'false' }}"
        
        echo "运行参数："
        echo "目标国家: $TARGET_COUNTRIES"
        echo "每个国家最少IP数: $MIN_IPS_PER_COUNTRY"
        echo "最大并发数: $MAX_CONCURRENT"
        echo "测试中国网络: $TEST_CHINA_NETWORK"
        
        # 运行脚本并传递参数
        python ip_tester.py --target-countries "$TARGET_COUNTRIES" --min-ips "$MIN_IPS_PER_COUNTRY" --max-concurrent "$MAX_CONCURRENT" --test-china-network "$TEST_CHINA_NETWORK"
    
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add country_results/
        git commit -m "Update IP test results for $TARGET_COUNTRIES - $(date)" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
